services:
  # Backend API service
  - type: web
    name: ticket-management-api
    runtime: node
    rootDir: backend
    buildCommand: npm install --no-audit --prefer-offline && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://shared-cluster:shared-cluster-23513@shared-cluster.wtzmfhn.mongodb.net/chemreq

  # Frontend static site
  - type: static
    name: ticket-management-frontend
    buildCommand: npm install --no-audit --prefer-offline && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: ticket-management-api
          type: web
          property: url